
#Settings for the Blinds
[Blinds]
	#Searches X-Blocks below and X/2 to the sides of the clicked blind for others and opens/closes them too
	#Range: 0 ~ 100
	searchRadius = 6
	#Opens blinds from the topmost blind on if true
	opensFromRoot = true

