#modifies the size of the leaves
#Range: 1 ~ 20
leafSize = 3
#modifies how long it takes for the leaves to disappear
#Values over 2000 are not recommend
#Range: > 100
leafLifespan = 500
#modifies the amount of leaves that are spawning
#Values over 10000 are not recommend
#Range: > 0
leafSpawnRate = 1
#modifier the amount of leaves are spawning from conifer trees
#Values over 10000 are not recommend
#Range: > 0
coniferLeafSpawnRate = 1
#whether player placed blocks should also drop leaves
dropFromPlayerPlacedBlocks = true
#how much room below the leaves block is needed for the leaves to spawn
#Range: 1 ~ 20
minimumFreeSpaceBelow = 3
#disable wind effects
disableWind = false
#windless dimensions
windlessDimension = ["minecraft:the_nether", "minecraft:the_end"]

["Serene Seasons"]
	#spawnrate modifier per season/subseason
	#Format: '<season>:<modifier>'; eg 'SUMMER:0.23'
	#Subseasons override seasons
	#Allowed seasons: SPRING,SUMMER,AUTUMN,WINTER,EARLY_SPRING,MID_SPRING,LATE_SPRING,EARLY_SUMMER,MID_SUMMER,LATE_SUMMER,EARLY_AUTUMN,MID_AUTUMN,LATE_AUTUMN,EARLY_WINTER,MID_WINTER,LATE_WINTER
	seasonFallRate = ["SPRING:0.1", "AUTUMN:2", "SUMMER:0.3", "WINTER:0.1"]

